### ISSUE TITLE
How to implement it?

### ISSUE THREAD

**Issue by stevevaius2015** [MiscellaneousStuff/openai-whisper-cpu#4]
Could you provide a bit step by step instructions for this on a win10 machine and an example run? I am very interested to check performance of this modification. I tried greganov cpu solution for this.

**Comment by ClashSAN** [comment]
@stevevaius2015 To run: `python3 custom_whisper.py audio/ceave1.mp3 --language English --model base.en`

make sure you have a folder and file to output to.

**Comment by ClashSAN** [comment]
full instructions:

    git clone https://github.com/MiscellaneousStuff/openai-whisper-cpu
    git submodule init
    git submodule update
    pip install -e ./whisper

in the folder, do `python3 custom_whisper.py audio/ceave1.mp3 --language English --model base.en`

**Comment by enrybds** [comment]
Why i get this erro when i try pip install -e ./whisper?

WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
ERROR: ./whisper is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)

**Comment by jinbombay** [comment]
I am having troubles updating whisper.  Complete coding noob here.  

Could you please give further step by step instructions on how to install this update to whisper using python.  I don't understand how to fork the repo in this case for whisper.

**Comment by MiscellaneousStuff** [comment]
Hello there. Ok the basic idea is that the original `whisper` repo from OpenAI contains code which allows you to run the model either at 100% or 50% (32-bit floating point or 16-bit floating point). The problem is that, to use this repo it needs to use a specific in-built neural network layer called "nn.Linear()" instead of the custom "Linear()" layer.

What this means for you in simple terms is that you just need to get this repo and the submodule (which is another GitHub repository which this project depends on, which can be found [here](https://github.com/MiscellaneousStuff/whisper) and it will all just work together.

To do this, follow each instruction below step by step and you should find that it just works:

```bash
git clone https://github.com/MiscellaneousStuff/openai-whisper-cpu
git submodule init
git submodule update
pip install -e ./whisper
```
