### ISSUE TITLE
how to use for non-English language?

### ISSUE THREAD

**Issue by gnmarten** [MiscellaneousStuff/openai-whisper-cpu#5]
error when running the script custom_whisper.py with "--language German": "model German not found (available models: ...)"

whisper itself downloads the required model when doing "--language German" (but can't run it because insufficient GPU memory of course)

**Comment by MiscellaneousStuff** [comment]
Hi there, thank you for your interest in the project!
This is due to our documentation for the custom script being a bit unclear.

To use this module and transcribe `German` videos, follow the standard installation instructions:

```bash
git clone https://github.com/MiscellaneousStuff/openai-whisper-cpu
git submodule init
git submodule update
pip install -e ./whisper
```

Then create a directory called "audio" within "openai-whisper-cpu" so "openai-whisper-cpu/audio".

And then place your `German` audio file in the audio directory, for example. "audio/GermanSample.mp3".

Now, to transcribe this `German` language audio file, use the following command from the "openai-whisper-cpu" directory.

```bash
python ./script/custom_whisper.py audio/GermanSample.mp3 --language German --model base
```

Feel free to change the base model to any other size model from one of the following: tiny, base, small, medium, large. However, I would be careful about using the `large` model as some users have reported a drop in accuracy when using that size model with Dynamic Quantization (the technique used to improve CPU performance in this project).

Best of luck! Any other questions, feel free to ask.
